name: Manual Parallel WDIO Tests

# on:
#   push:
#     branches:
#       - main
on: 
  workflow_dispatch:
    # inputs:
    #   # logLevel:
    #   #   description: 'Log level'     
    #   #   required: true
    #   #   default: 'warning'
    #   hub-url:
    #     description: 'Test scenario tags'
    #     default: 
jobs:
  smoke:
    uses: ./.github/workflows/execution-workflow.yml
    with:
      suite_name: "smoke"
      runner_label: "ubuntu-latest"
  parallel-tests:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        suite: ["suite1 suite2", "suite3 suite4","release1", "smoke"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'


      - name: Install node dep
        run: npm install

      - name: Run WDIO Tests
        run: |
          pwd
          ls
          date
          npx wdio --suite ${{ matrix.suite }}
  multiple_suites:
    needs: smoke
    uses: ./.github/workflows/execution-workflow.yml
    with:
        suite_name: "suite1 suite2"
        runner_label: "ubuntu-latest"
