name: not-working-calling-jobs-updated-sample

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Provide application name'
        required: true
      runner_label:
        description: 'Provide runner label'
        required: true
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  
jobs:
  infra_provition:
    uses: ./.github/workflows/aws-sample.yml
    with:
      max_runners: 2
  configure:
    needs: infra_provition
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c .${{ github.event.inputs.app-name }} < ./config.json)" >> $GITHUB_OUTPUT
  test_execution:
    needs: configure
    uses: ./.github/workflows/local-run.yml
    with:
      runner_label: ${{inputs.runner_label}}
  # print:
  #   runs-on: ubuntu-latest
  #   needs: configure
  #   strategy:
  #     matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
  #   steps:
  #    - run: echo ${{ matrix.test }}

  # ReuseableMatrixJobForDeployment:
  #   needs: configure
  #   strategy:
  #     max-parallel: 2
  #     fail-fast: false
  #     matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
  #   uses: ./.github/workflows/execution-workflow.yml
  #   with:
  #     test_case: ${{ matrix.test }}
  #     project: ${{ matrix.project }}
  #     runner_label: "self-hosted"
  #     # username: ${{ matrix.username }}
  #   # secrets:
  #   #   password: ${{matrix.password}}
  tearDown:
    needs: test_execution
    uses: ./.github/workflows/aws-sample.yml
    if: always()
    with:
      teardown: "true"
